# Generated by Django 5.2.4 on 2025-09-26 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HumanTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_id', models.IntegerField(default=0)),
                ('types', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('body_structure', models.CharField(blank=True, max_length=200, null=True)),
                ('dress_colour', models.CharField(blank=True, max_length=200, null=True)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(default=0)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'human_track',
            },
        ),
    ]
