# Generated by Django 5.2.7 on 2026-01-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_humantrack_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognizedFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=50)),
                ('emp_id', models.CharField(blank=True, max_length=50, null=True)),
                ('similarity_score', models.FloatField()),
                ('similarity_id', models.CharField(blank=True, max_length=50, null=True)),
                ('image_path', models.CharField(max_length=255)),
                ('capture_date_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'recognized_faces',
                'ordering': ['capture_date_time'],
            },
        ),
        migrations.DeleteModel(
            name='HumanTrack',
        ),
    ]
