# Generated by Django 5.2.7 on 2026-01-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_recognizedface_delete_humantrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=50)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_id', models.CharField(max_length=50)),
                ('emp_type', models.CharField(blank=True, max_length=50, null=True)),
                ('dept', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('agree_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employees',
                'unique_together': {('company_id', 'emp_id')},
            },
        ),
    ]
