# Generated by Django 5.2.7 on 2026-01-03 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_filename', models.CharField(max_length=255)),
                ('video_path', models.CharField(max_length=500)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.employee')),
            ],
            options={
                'db_table': 'face_recordings',
            },
        ),
    ]
