# Generated by Django 5.2.7 on 2026-01-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_facerecording'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facerecording',
            name='emp',
        ),
        migrations.AddField(
            model_name='facerecording',
            name='emp_id',
            field=models.CharField(default='UNKNOWN', max_length=50),
            preserve_default=False,
        ),
    ]
