# Generated by Django 5.2.7 on 2026-01-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognizedface',
            name='capture_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
