# Generated by Django 5.2.7 on 2026-01-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_employee_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('meeting', 'Meeting Rule'), ('allowed_place', 'Allowed Place'), ('restricted_zone', 'Restricted Zone'), ('in_out', 'In / Out Time Rule'), ('group', 'Group Gathering'), ('phone', 'Phone Usage')], max_length=30)),
                ('rules_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
