# Generated by Django 5.2.7 on 2026-01-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognizedface',
            name='phone_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recognizedface',
            name='phone_distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
