# Generated by Django 5.2.7 on 2026-01-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_recognizedface_phone_detected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognizedface',
            name='phone_mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
