# Generated by Django 5.2.7 on 2026-01-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_recognizedface_phone_mail_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognizedface',
            name='activity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
