# Generated by Django 5.2.7 on 2026-01-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_recognizedface_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognizedface',
            name='bbox',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
