# Generated by Django 5.2.7 on 2026-02-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_recognizedface_bbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognizedface',
            name='helmet_detected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('meeting', 'Meeting Rule'), ('allowed_place', 'Allowed Place'), ('restricted_zone', 'Restricted Zone'), ('in_out', 'In / Out Time Rule'), ('group', 'Group Gathering'), ('phone', 'Phone Usage'), ('helmet', 'Helmet Safety Rule')], max_length=30),
        ),
    ]
