# Generated by Django 5.2.7 on 2026-02-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_recognizedface_helmet_detected_alter_rule_rule_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_dept', models.CharField(blank=True, max_length=100, null=True)),
                ('total_emp', models.IntegerField(blank=True, null=True)),
                ('present_emp', models.IntegerField(blank=True, null=True)),
                ('missing_emp', models.TextField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('allowed_department', models.CharField(blank=True, max_length=100, null=True)),
                ('zone_type', models.CharField(blank=True, max_length=50, null=True)),
                ('person', models.CharField(blank=True, max_length=50, null=True)),
                ('break_type', models.CharField(blank=True, max_length=100, null=True)),
                ('close_count', models.IntegerField(blank=True, null=True)),
                ('detected_count', models.IntegerField(blank=True, null=True)),
                ('known_employee', models.TextField(blank=True, null=True)),
                ('unknown_visitor', models.IntegerField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_send',
            },
        ),
    ]
