# Generated by Django 5.2.7 on 2026-02-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_emailsend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsend',
            old_name='category',
            new_name='rule_category',
        ),
    ]
